### ISSUE TITLE
KeyError: 'ns_targets' when creating a reserved domain

### ISSUE THREAD

**Issue by takehikokodama** [ngrok/ngrok-api-python#12]
When I create a reserved domain, I get the following error while the domain is created in ngrok.

```
>>> import os
>>> import ngrok
>>> ng = ngrok.Client(os.getenv('API_KEY'))
>>> ng.reserved_domains.create(name="test.example.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/takehiko.kodama/Documents/test/ngrok/env/lib/python3.9/site-packages/ngrok/services.py", line 2487, in create
    return ReservedDomain(self._client, result)
  File "/Users/takehiko.kodama/Documents/test/ngrok/env/lib/python3.9/site-packages/ngrok/datatypes.py", line 2694, in __init__
    ReservedDomainCertStatus(client, props["certificate_management_status"])
  File "/Users/takehiko.kodama/Documents/test/ngrok/env/lib/python3.9/site-packages/ngrok/datatypes.py", line 2849, in __init__
    ReservedDomainCertJob(client, props["provisioning_job"])
  File "/Users/takehiko.kodama/Documents/test/ngrok/env/lib/python3.9/site-packages/ngrok/datatypes.py", line 2907, in __init__
    if props["ns_targets"] is not None
KeyError: 'ns_targets'
```

**Comment by russorat** [comment]
@takehikokodama we just released a new version of this client. can you update and verify the issue is resolved?

**Comment by takehikokodama** [comment]
@russorat I confirmed it's been fixed, Thank you!
